sudo: false

language: python

install:
  - pip install -r 'requirements.txt'

matrix:
    include:
        # python 2.7
        - python: 2.7
          env: >
            SRCPATH=src/
            TESTPATH=test/
script:
  - pep8 src/*.py
  - coverage run test/exam1_test.py
  
after_success:
  - bash <(curl -s https://codecov.io/bash)
